resources:

- name: platform-automation-tasks
  type: s3
  source:
    access_key_id: ((s3_access_key_id))
    bucket: ((s3_buckets_pivnet_products))
    endpoint: ((s3_endpoint))
    secret_access_key: ((s3_secret_access_key))
    regexp:  platform-automation/platform-automation-tasks-(.*).zip

- name: platform-automation-image
  type: s3
  source:
    access_key_id: ((s3_access_key_id))
    bucket: ((s3_buckets_pivnet_products))
    endpoint: ((s3_endpoint))
    secret_access_key: ((s3_secret_access_key))
    regexp: platform-automation/platform-automation-image-(.*).tgz

- name: configuration
  type: git
  source:
    uri: ((repo))
    private_key: ((git.private_key))
    branch: ((config-branch))

interpolate-creds: &interpolate-creds
  image: platform-automation-image
  file: platform-automation-tasks/tasks/credhub-interpolate.yml
  params:
    CREDHUB_CLIENT: ((credhub-client))
    CREDHUB_SECRET: ((credhub-secret))
    CREDHUB_SERVER: ((credhub-server))
    CREDHUB_CA_CERT: ((credhub-ca-cert.ca))
    PREFIX: "/concourse/mat"
    INTERPOLATION_PATHS: ((foundation))
    SKIP_MISSING: false
  input_mapping:
    files: configuration
  output_mapping:
    interpolated-files: interpolated-creds
jobs:
- name: configure-boshdir
  plan:
    - get: platform-automation-image
      params:
        globs: ["*image*.tgz"]
        unpack: true
    - get: platform-automation-tasks
      params:
        globs: ["*tasks*.zip"]
        unpack: true
    - get: configuration
    - task: interpolate-creds
      <<: *interpolate-creds
    - task: configure-authentication
      image: platform-automation-image
      file: platform-automation-tasks/tasks/configure-authentication.yml
      attempts: 3
      params:
        ENV_FILE: ((foundation))/config/env.yml
        AUTH_CONFIG_FILE: ((foundation))/config/auth.yml
      input_mapping:
        env: interpolated-creds
        config: interpolated-creds
    - task: configure-director
      image: platform-automation-image
      file: platform-automation-tasks/tasks/configure-director.yml
      params:
        ENV_FILE: ((foundation))/config/env.yml
        DIRECTOR_CONFIG_FILE: ((foundation))/config/director.yml
      input_mapping:
        config: interpolated-creds
        env: interpolated-creds
    - task: apply-director-changes
      image: platform-automation-image
      file: platform-automation-tasks/tasks/apply-director-changes.yml
      params:
        ENV_FILE: ((foundation))/config/env.yml
      input_mapping:
        env: interpolated-creds

- name: upload-and-stage-pas
  plan:
    - aggregate:
        - get: platform-automation-image
          params:
            unpack: true
        - get: platform-automation-tasks
          params:
            unpack: true
        - get: configuration
    - task: interpolate-creds
      <<: *interpolate-creds
    - task: download-pas
      image: platform-automation-image
      file: platform-automation-tasks/tasks/download-product.yml
      params:
        CONFIG_FILE: ((foundation))/download-config/pas.yml
      input_mapping:
        config: interpolated-creds
      output_mapping:
        downloaded-product: pas-product
        downloaded-stemcell: pas-stemcell
    - task: upload-and-stage-product
      image: platform-automation-image
      file: platform-automation-tasks/tasks/upload-and-stage-product.yml
      params:
        ENV_FILE: ((foundation))/config/env.yml
      input_mapping:
        product: pas-product
        env: interpolated-creds
    - task: upload-pas-stemcell
      image: platform-automation-image
      file: platform-automation-tasks/tasks/upload-stemcell.yml
      params:
        ENV_FILE: ((foundation))/config/env.yml
      input_mapping:
        env: interpolated-creds
        stemcell: pas-stemcell

- name: configure-pas
  plan:
    - aggregate:
        - get: platform-automation-image
          params:
            unpack: true
        - get: platform-automation-tasks
          params:
            unpack: true
        - get: configuration
    - task: interpolate-creds
      <<: *interpolate-creds
    - task: configure-pas
      image: platform-automation-image
      file: platform-automation-tasks/tasks/configure-product.yml
      input_mapping:
        config: interpolated-creds
        env: interpolated-creds
      params:
        ENV_FILE: ((foundation))/config/env.yml
        CONFIG_FILE: ((foundation))/config/pas.yml