resources:

- name: platform-automation-tasks
  type: s3
  source:
    access_key_id: ((s3_access_key_id))
    bucket: ((s3_buckets_pivnet_products))
    endpoint: ((s3_endpoint))
    secret_access_key: ((s3_secret_access_key))
    regexp:  platform-automation/platform-automation-tasks-(.*).zip

- name: platform-automation-image
  type: s3
  source:
    access_key_id: ((s3_access_key_id))
    bucket: ((s3_buckets_pivnet_products))
    endpoint: ((s3_endpoint))
    secret_access_key: ((s3_secret_access_key))
    regexp: platform-automation/platform-automation-image-(.*).tgz

- name: configuration
  type: git
  source:
    uri: ((repo))
    private_key: ((git.private_key))
    branch: ((config-branch))

# This task is used in multiple jobs
# The yaml anchor "*interpolate-creds" is used in its place
interpolate-creds: &interpolate-creds
  image: platform-automation-image
  file: platform-automation-tasks/tasks/credhub-interpolate.yml
  params:
    CREDHUB_CLIENT: ((credhub-client))
    CREDHUB_SECRET: ((credhub-secret))
    CREDHUB_SERVER: ((credhub-server))
    CREDHUB_CA_CERT: ((credhub-ca-cert))
    PREFIX: '/concourse/mat/azpcf'
    INTERPOLATION_PATHS: azpcf
    SKIP_MISSING: true
  input_mapping:
    files: configuration
  output_mapping:
    interpolated-files: interpolated-creds    
jobs:
- name: configure-boshdir
  plan:
    - aggregate:
      - get: platform-automation-image
        params:
          globs: ["*image*.tgz"]
          unpack: true
      - get: platform-automation-tasks
        params:
          globs: ["*tasks*.zip"]
          unpack: true
      - get: configuration
      - task: interpolate-creds
        <<: *interpolate-creds
      - task: configure-authentication
        image: platform-automation-image
        file: platform-automation-tasks/tasks/configure-authentication.yml
        attempts: 3
        input_mapping:
          env: interpolated-creds
          config: interpolated-creds
 